= Shanon Seet - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:important-caption: :exclamation:

== PROJECT: FOP Manager

---

== About the Project

In this semester for our Software Engineering project, my team and I were tasked with developing an existing Command Line Interface addressbook application. We decided to enhance it to an application that manages camp participants' information for NUS Freshmen Orientation Camp Project Directors, and hence the birth of *FOP Manager*. This enhanced application enables Project Directors to view and modify participants' contact details with ease, supporting also the separation of Freshmen participants from Orientation Group Leader (OGL) participants, the arrangement of participants into groups and houses, and a Graphic User Interface that displays contact details and command results in an appealing format.

In this project, I was in charge of creating the commands to support the addition and modification of groups and houses. The following sections showcase these features, as well as the relevant sections I have added to the user and developer guides, in more detail.

In this document, the following styles and formatting have been used:

|============================================================
| :exclamation: |This symbol indicates important information.
|`add_g` |A grey highlight indicates that this is a command that can be inputted into the command line and executed by the application.
|`_Group_` |Italicised words in grey highlight indicate the name of a class or object used in the application.
|============================================================


== Summary of Contributions

This section shows a summary of my coding, documentation, and other helpful contributions to the team project.

*Enhancement Added*: I added the ability to create and modify `_House_` and `_Group_` objects
* What it does: It allows users to add, edit and delete houses and groups to their camp, which in turn allows them to group participants, as is done in camps.
* Justification: This is a core feature of our *FOP Manager* application. Being tailored to manage participant details in Freshmen Orientation Programmes, having groups and houses are essential to organising participants as camp organisers would usually do when planning camps.
* Highlights: This feature is one of the core components that other enhancements build upon. An in-depth analysis of design alternatives was necessary to determine the storage of `_House_` and `_Group_` objects as it affected how efficiently data could be extracted and used. The implementation was also challenging as it required the addition of a group attribute to the `_Participant_` (previously named `_Person_`) class, as well as required changes to existing basic commands such as adding and editing a `_Participant_`.

* *Minor enhancement*: Added a size command that allows the user to view the sizing details of the camp.

* *Code contributed*: Click these links to see a sample of my code: https://github.com/shanseet/T08-Fork/blob/master/src/main/java/seedu/address/logic/commands/EditGroupCommand.java[Edit Group Command], https://github.com/shanseet/T08-Fork/blob/master/src/main/java/seedu/address/logic/commands/SizeCommand.java[Size Command]

* *Other contributions*:

** Project Management:
*** Created labels and issues and assigned them to team members to keep track of team progress
*** Managed milestones v1.2 to v1.4
** Documentation:
*** Made major changes to reformat and update User Guide and Developer Guide to include new features, as well as make it more reader-friendly: https://github.com/cs2113-ay1819s2-t08-4/main/pull/74[#74], https://github.com/cs2113-ay1819s2-t08-4/main/pull/102[#102]
** Community:
*** Gave consistent feedback to team members to improve their implemented features
*** Gave suggestions for other teams in the class of their User Guide and Developer Guide

_{you can add/remove categories in the list above}_

== Contributions to the User Guide

Our team also updated the original addressbook User Guide with instructions for the enhancements that we had added. The following is an excerpt from our FOP Manager User Guide to show additions I made for managing `_House_` and `_Group_` objects:

=== Edit Group
*`edit_g OLDGROUPNAME NEWGROUPNAME: Edits a group name.*

****
* Edits the group named `OLDGROUPNAME` to `NEWGROUPNAME`
* The `GROUP` of all participants within the old group is automatically updated.

[WARNING]
`OLDGROUPNAME` must exist in the current list of groups

[WARNING]
`NEWGROUPNAME` must not exist in the current list of groups

[NOTE]
Group names are not case-sensitive

=== View Group
*`view_g`: Views the list of all groups added so far, along with the house they belong to*

Example:

* Groups `R1` and `R2` have been added under the house `Red`. +
`view_g` returns `[(R1, Red), (R2, Red)]`.

include::https://github.com/cs2113-ay1819s2-t08-4/main/blob/master/docs/UserGuide.adoc[tag=ViewHouse]

== Contributions to the Developer Guide

Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project.

==== Group and House Management

*FOP Manager* supports group and house commands, to reflect the structure of an actual Freshmen Orientation camp. Group and house management refer to how groups and houses are created and modified, as well as viewed, and how they support the addition of participants.

==== Current Implementation

In *FOP Manager*, groups and houses can be added, edited and deleted.

Add

* `add_h` creates a new house and adds it to the `UniqueHouseList` in the `AddressBook` object.
* `add_g` adds a new group with its corresponding house name to the `UniqueGroupList` in the `AddressBook` object.

Edit

* `edit_h` edits the name of a house in `UniqueHouseList`, as well as changes the house name of all groups within the house in `UniqueGroupList`.
* `edit_g` edits the name of a group in `UniqueGroupList`, as well as changes the group name of all participants with that group name in `UniqueParticipantList`.

Delete

* Deleting of house objects require there to be no groups within that house.
* Deleting of group objects require there to be no participants within that group.

==== Design Considerations

===== Aspect: Storage of group and house lists

* *Alternative 1:* Storing groups and houses within a single list of houses that contain differing number of groups
** Pros: Easy management of data
** Cons: Violates separation of concerns principle by requiring access and modification made to houses, whenever only group level data is required
* *Alternative 2 (current choice):* Storing groups and houses in 2 separate lists
** Pros: House objects are not affected by the operations done to the groups stored within it
** Cons: More computationally expensive to identify the groups within a house.

===== Aspect: Deleting a group object requirements

* *Alternative 1:* No requirements when groups are deleted.
** Pros: User can delete a group much more easily
** Cons: Participants in the deleted group will belong to no group
* *Alternative 2 (current choice):* Requires a group to contain no participants before it can be deleted.
** Pros: User can be sure to not delete a group with participants in it accidentally
** Cons: Participants must be manually removed from the group before being deleted

[NOTE]
Camp organizers rarely intend to remove a filled group. Requiring a group to be empty before being deleted acts as a fail-safe to ensure that filled groups are not accidentally removed, resulting in participants having to be manually added back to the group.

===== Aspect: Duplicate group names under different houses

* *Alternative 1 (current choice):* Duplicate group names are not allowed.
** Pros: Groups can be searched for by name without specifying its house
** Cons: Simple names such as 1 and 2 cannot be used for different houses at initial planning stage
* *Alternative 2:* Duplicate group names under different houses are allowed.
** Pros: User can easily name groups without too much thought
** Cons: User must always specify house name when searching for a specific group
