= Shanon Seet - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:xrefstyle: full
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
:experimental:
endif::[]

Hello! I am a Year 2 Computer Engineering student studying in the National University of Singapore (NUS). In NUS, Computer Engineering a combined major under both School of Computing and the Faculty Engineering. As someone rather new to the industry, I am always excited to learn and experience new things. I have done both hardware and software projects in my last 2 years in university, and in this document I will be showing you a portfolio of my contributions to my team's Software Engineering project over this semester.

== PROJECT: _FOP Manager_

---

== About The Project

My team and I were tasked with developing an existing Command Line Interface addressbook application. We decided to enhance it to an application that manages camp participants' information for NUS Freshmen Orientation Camp Project Directors, and hence the birth of _FOP Manager_. This enhanced application allows Project Directors to view and modify participants' contact details with ease, and also supports Freshmen and Orientation Group Leader (OGL) participants, arranging participants into groups and houses, and a Graphic User Interface that displays contact details and command results in an appealing format, among other things.

In this project, I was in charge of creating the commands that support the addition and modification of groups and houses.

== About This Document

This document showcases the features I did, samples of my code, as well as relevant sections I added to the User and Developer Guides.

In this document, the following styles and formatting have been used:

****

NOTE: This symbol indicates important information.

`add_g`: Grey highlight indicates that this is a command that can be inputted into the command line and executed by the application.

`_Group_`: Italicised words in grey highlight indicate the name of a class or object used in the application.

****

== Summary of Contributions

This section shows a summary of my coding, documentation, and other helpful contributions to the team project.

In this project, I was in charge of creating the logic to support our app's feature of `_Group_` and `_House_` management.

*Major enhancements*:

. Adding, editing and deleting groups and houses
* _Commands_: `add_g`, `add_h`, `edit_g`, `edit_h`, `delete_g`, `delete_h`
* _Purpose_: These commands allow users to add, edit and delete `_House_` and `_Group_` objects, enabling them to group participants according to their camp grouping.
* _Justification_: Being tailored to manage participant details in Freshmen Orientation camps, having groups and houses are essential to organising participants as camp organisers normally do when planning camps.
* _Highlights_: These commands are a core component of the project that other commands such as `randomize` build upon. More details of how I implemented them can be found below in the <<DesignConsiderations,Design Considerations>> of the section of the Developer Guide covering group and house management. The implementation of these commands was challenging as it required changes to basic commands like `add` and `edit`, as well as to the overall model of the app.

. Listing participants by houses and groups
* _Commands_: `list_h`, `list_g`
* _Purpose_: These commands allow the user to list the participants in a specified house or group.
* _Justification_: Listing the participants in the same group and same house is necessary for the user to filter through data quickly, especially when managing a large camp. It also allows the user to see the current size of a specific group or house.
* _Acknowledgement_: These commands were modified from the `list_o` and `list_f` commands, making use of predicates as well to identify a different list of participants.
* _Highlights_: The `list_g` command supports listing participants without a group (i.e. an empty `_Group_` field) by entering the command `list_g empty`. This allows the user to quickly see which participants have not been placed in groups, making group assignments much easier and ensuring no participants have been overlooked in group placement.

. Viewing houses and groups
* _Commands_: `view_h`, `view_g`
* _Purpose_: These commands allow the user to view the houses and groups they have added so far.
* _Justification_: After adding a house and a group, the user may want to edit its name, or delete it. Also, users can only add groups to existing houses, and add participants to existing groups. Each of these commands require the exact house or group name to be specified. The commands `view_h` and `view_h` help the user know which houses and groups have been created so far, and can therefore be added to, modified or deleted.

*Minor enhancement*:

. _Size command_
 * _Command_: `size`
 * _Purpose_: This command allows the user to view the sizing details of the camp.

*Code contributed*:

* _Functional code_: https://github.com/shanseet/T08-Fork/blob/master/src/main/java/seedu/address/logic/commands/AddGroupCommand.java[Add Group Command], https://github.com/shanseet/T08-Fork/blob/master/src/main/java/seedu/address/logic/commands/EditGroupCommand.java[Edit Group Command], https://github.com/shanseet/T08-Fork/blob/master/src/main/java/seedu/address/logic/commands/ListGroupCommand.java[List Group Command]
* _Test code_: https://github.com/shanseet/T08-Fork/blob/master/src/test/java/seedu/address/logic/commands/EditGroupCommandTest.java[Edit Group Commmand Test], https://github.com/shanseet/T08-Fork/blob/master/src/test/java/seedu/address/logic/commands/EditHouseCommandTest.java[Edit House Command Test], https://github.com/shanseet/T08-Fork/blob/master/src/test/java/seedu/address/model/grouping/FindGroupHousePredicateTest.java[Find Group and House Predicate Test]
* Check out more of my code on Project Code Dashboard https://nuscs2113-ay1819s2.github.io/dashboard-beta/#=undefined&search=shanseet[here].

*Other contributions*:

* _Project Management_:
** In charge of the issue tracker
** Managed milestones v1.2 to v1.4
* _Documentation_:
** Made major changes to reformat and update User Guide and Developer Guide to include new features, as well as make it more reader-friendly: https://github.com/cs2113-ay1819s2-t08-4/main/pull/74[#74], https://github.com/cs2113-ay1819s2-t08-4/main/pull/102[#102]
* _Community_:
** Gave consistent feedback to team members to improve their implemented features
** Gave suggestions for other teams in the same tutorial group to improve their User Guide and Developer Guide

== Contributions to the User Guide

Our team updated the original AB4 User Guide with instructions for the enhancements that we had added. In this document there are additional icons used, as shown below:

****
TIP: This is a tip. Following these suggestions will make using FOP Manager much simpler.

WARNING: This is a warning and they need to be heeded for FOP Manager to work smoothly.
****

The following is an excerpt from the User Guide showing the additions I made for editing `_House_` and `_Group_` objects:

=== Editing Houses and Groups
include::../UserGuide.adoc[tag=editgrouphouse]

Check out the full User Guide https://github.com/shanseet/T08-Fork/blob/master/docs/UserGuide.adoc[here].

== Contributions to the Developer Guide

Shown below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project.

include::../DeveloperGuide.adoc[tag=GroupHouseManagement]

Check out the full Developer Guide https://github.com/shanseet/T08-Fork/blob/master/docs/DeveloperGuide.adoc[here].
